version: '2'
services:
  mysql:
    container_name: checkout_db
    restart: always
    image: mysql:latest
    command: --lower_case_table_names=1
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'admin' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - checkout-datavolume:/var/lib/mysql
volumes:
  checkout-datavolume: